### ISSUE TITLE
Example broken on real hardware – black screen, XMB (kind of) inaccesible

### ISSUE THREAD

**Issue by prochazkaml** [wargio/NoRSX#9]
I attempted to build the example of this (as far as I can tell) wonderful 2D library, however, upon installing the compiled .pkg file on my console (CECHL04 PAL running REBUG 4.86.1 Lite), it just drops me into a black screen, where I cannot even access the XMB by pressing the PS button. If I press Start, nothing happens, so it is safe to assume that the example program has crashed.

However, the console itself isn't _completely_ dead, I can still sort of control it. When I press the PS button to enter XMB (which I cannot see) and then hold L3+R3 (which is a webMAN hotkey for turning the on-screen FPS counter on), it still plays the trophy sound effect to indicate that it has enabled the FPS counter.

In fact, I can still connect to the webMAN interface from my PC, where I can see that the example program is still running and it even seems to allow me to dump the process memory (please let me know if that could be useful), however, when I click on "Exit", it just waits for a few seconds, then the console beeps three times and restarts itself.

Of course, when I try to power the system off using the power button, it just gives me the three beeps, keeps blinking for a bit and then shuts finally off.

On RPCS3, however, the exact same package, after installing, ran completely fine. I installed the same CFW into the emulator, if that matters.

**Comment by wargio** [comment]
that is weird, unless something has changed on PSL1GHT side

**Comment by prochazkaml** [comment]
It is. I seems that [PSL1GHT](https://github.com/ps3dev/PSL1GHT) and [ps3toolchain](https://github.com/ps3dev/ps3toolchain)'s last commit come from the end of 2021, so no recent changes there (compared to this repo). There are 2 commits from April of this year on the [ps3libraries](https://github.com/ps3dev/ps3libraries) repo, but those only involve changing a couple of things regarding the zlib url.

I will try installing PSL1GHT again, perhaps my installation is broken. (I doubt it, since other examples supplied with PSL1GHT itself compile fine, but you can never be 100% sure.)

If you still have access to your toolchain, what version of GCC do you have installed? It seems that PSL1GHT has at some point upgraded from using GCC 4.X to 7.2, and some report that the new toolchain causes incompatibilities.

Do you still have a compiled .pkg of this example somewhere sitting around that you could please share here? Perhaps there is just some problem with my console/its firmware that does not play nicely with NoRSX.

**Comment by wargio** [comment]
when i used to develop on it it was gcc5 or 6

**Comment by prochazkaml** [comment]
Alright, so I built a fresh new toolchain from the ps3toolchain repo, but still, no dice.

By the way, this library is supposed to be automatically pulled and compiled when building the toolchain itself (see ps3libraries, it's included in there) - not that anyone who doesn't dive into the code would notice, since the toolchain build process crashes at some point before compiling your library due to it failing to download polarssl, which no longer exists, as it has apparently been renamed years ago.

It seems to me that the entire PS3 homebrew scene is slowly rotting away, with decades of no longer working code left behind...

It's a shame, and I'm really tempted to find an old pre-built version of PSL1GHT posted somewhere, grab my trusty old Windows XP VM and try to get it all working over there (since I can forget about running decade old binaries on Linux). Maybe I will finally get RSXGL to compile as well!

**Comment by prochazkaml** [comment]
Alright, so I've tried to compile some samples straight from the PSL1GHT repo, more specifically [blitting](https://github.com/ps3dev/PSL1GHT/tree/master/samples/graphics/blitting) and [cairo](https://github.com/ps3dev/PSL1GHT/tree/master/samples/graphics/cairo). The blittting one works on real hardware (but crashes in an emulator), meanwhile the cairo example does the same as NoRSX - black screen on real hardware, perfectly functional on an emulator.

I just don't know anymore.

**Comment by prochazkaml** [comment]
Alright, so I pulled some 7 year old Docker container with PSL1GHT pre-installed, and sure enough, it runs:

![NoRSX running very poorly](https://user-images.githubusercontent.com/41787099/178208933-4ab8aaf0-6d47-4ea4-b78a-04e18e444623.jpeg)

The performance isn't great though, and pressing triangle crashes the example program. But it's progress!

Actually, I compiled the example against the 7 year old NoRSX which came pre-compiled with the container, as the current version of this library does not even compile in the old toolchain.

**Comment by wargio** [comment]
it's a software library, no HW accelleration
i suggest to use Tiny3D

**Comment by prochazkaml** [comment]
I knew that, but I thought that the PS3 could still render some stuff at a decent rate only using software...

Thank you for pointing me to Tiny3D, your fork (including all examples, except the soundlib one, its graphics are quite messed up, but nothing crashes) appears to work great even with my latest toolchain!

So, in conclusion, if anyone is having the same issue: get an older version of the toolchain ([this Docker image seems to work fine with its precompiled version of NoRSX](https://registry.hub.docker.com/r/psl1ght/psl1ght)), the latest one appears to have some unknown incompatibilities.

**Comment by wargio** [comment]
unfortunately i cannot fix this because i do not have a ps3 here with me.

**Comment by prochazkaml** [comment]
One thing I might be able to try is to compile an older version of this library against the new toolchain, as that was what came with the old precompiled toolchain (*and worked*). I kind of doubt that the new toolchain is at fault here, as other libraries (well, except cairo, which is still a mystery) appear to work fine. Perhaps some recent change here broke something? It's quite strange, and it's very much something I'd like to investigate.

(apologies for commenting so late, I was too busy playing around with your fork of tiny3D! I even managed to make my own custom 3D model renderer - I just converted an STL into a C include file containing a list of vertices and then I loop through each triangle and draw them! I know it might not sound that impressive, but I am not very experienced with 3D graphics, so it took me some time to figure all of it out...)
